# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate sample covariance
#' @description Returns the unnormalised sample covariance. Required as 
#' arma::cov() does not work for singletons.
#' @param data Data in matrix format
#' @param sample_mean Sample mean for data
#' @param n The number of samples in data
#' @param n_col The number of columns in data
#' @return One of the parameters required to calculate the posterior of the
#'  Multivariate normal with uknown mean and covariance (the unnormalised 
#'  sample covariance).
NULL

#' @name mvnSampler
#' @title Multivariate Normal mixture type
#' @description The sampler for the Multivariate Normal mixture model for batch effects.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: B - the number of batches present
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample from the priors for the multivariate normal
#' density.
#' @field calcBIC Calculate the BIC of the model.
#' @field logLikelihood Calculate the likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @title Sample batch mixture model
#' @description Performs MCMC sampling for a mixture model with batch effects.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
samplePaulModel <- function(X, K, B, labels, batch_vec, y_proposal_window, rho, theta, lambda, R, thin, concentration, verbose = TRUE, doCombinations = FALSE, printCovariance = FALSE) {
    .Call(`_BatchMixtureModel_samplePaulModel`, X, K, B, labels, batch_vec, y_proposal_window, rho, theta, lambda, R, thin, concentration, verbose, doCombinations, printCovariance)
}

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param fixed Binary vector of the items that are fixed in their initial label.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleSemiSupervisedPaulModel <- function(X, K, B, labels, batch_vec, fixed, y_proposal_window, rho, theta, lambda, R, thin, concentration, verbose = TRUE, doCombinations = FALSE, printCovariance = FALSE) {
    .Call(`_BatchMixtureModel_sampleSemiSupervisedPaulModel`, X, K, B, labels, batch_vec, fixed, y_proposal_window, rho, theta, lambda, R, thin, concentration, verbose, doCombinations, printCovariance)
}

#' @name mvtSampler
#' @title Multivariate t mixture sampler
#' @description The sampler for the Multivariate t mixture
#' model for batch effects.
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model.
#' \item Parameter: B - the number of batches present.
#' \item Parameter: labels - N-vector of unsigned integers denoting initial 
#' clustering of the data .
#' \item Parameter: batch_vec - N-vector of unsigned integers denoting 
#' the observed grouping variable.
#' \item Parameter: concentration - K- vector of the prior hyperparameter for 
#' the class weights
#' \item Parameter: X - an N x P matrix of the observed data to model.
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample values for the batch and class parameters from
#' their prior distributions.
#' @field calcBIC Calculate the BIC of the model.
#' @field logLikelihood Calculate the log-likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: x - a data point.
#' \item Parameter: b - the associated batch label.
#' }
#' @field updateBatchCorrectedData Transform the observed dataset based on 
#' sampled parameter values to a batch-corrected dataset.
NULL

gammaLogLikelihood <- function(x, shape, rate) {
    .Call(`_BatchMixtureModel_gammaLogLikelihood`, x, shape, rate)
}

invGammaLogLikelihood <- function(x, shape, scale) {
    .Call(`_BatchMixtureModel_invGammaLogLikelihood`, x, shape, scale)
}

wishartLogLikelihood <- function(X, V, n, P) {
    .Call(`_BatchMixtureModel_wishartLogLikelihood`, X, V, n, P)
}

invWishartLogLikelihood <- function(X, Psi, nu, P) {
    .Call(`_BatchMixtureModel_invWishartLogLikelihood`, X, Psi, nu, P)
}

#' @title Sample batch mixture model
#' @description Performs MCMC sampling for a mixture model with batch effects.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleMVN <- function(X, K, B, labels, batch_vec, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, R, thin, concentration) {
    .Call(`_BatchMixtureModel_sampleMVN`, X, K, B, labels, batch_vec, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, R, thin, concentration)
}

sampleMVT <- function(X, K, B, labels, batch_vec, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, t_df_proposal_window, R, thin, concentration) {
    .Call(`_BatchMixtureModel_sampleMVT`, X, K, B, labels, batch_vec, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, t_df_proposal_window, R, thin, concentration)
}

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param fixed Binary vector of the items that are fixed in their initial label.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleSemisupervisedMVN <- function(X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, R, thin, concentration) {
    .Call(`_BatchMixtureModel_sampleSemisupervisedMVN`, X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, R, thin, concentration)
}

sampleSemisupervisedMVT <- function(X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, t_df_proposal_window, R, thin, concentration) {
    .Call(`_BatchMixtureModel_sampleSemisupervisedMVT`, X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, t_df_proposal_window, R, thin, concentration)
}

