# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name gaussianSampler
#' @title Gaussian mixture type
#' @description The sampler for a mixture of Gaussians, where each feature is
#' assumed to be independent (i.e. a multivariate Normal with a diagonal 
#' covariance matrix).
#' @field new Constructor \itemize{
#' \item Parameter: K - the number of components to model
#' \item Parameter: labels - the initial clustering of the data
#' \item Parameter: concentration - the vector for the prior concentration of 
#' the Dirichlet distribution of the component weights
#' \item Parameter: X - the data to model
#' }
#' @field printType Print the sampler type called.
#' @field updateWeights Update the weights of each component based on current 
#' clustering.
#' @field updateAllocation Sample a new clustering. 
#' @field sampleFromPrior Sample from the priors for the Gaussian density.
#' @field calcBIC Calculate the BIC of the model.
#' @field itemLogLikelihood Calculate the likelihood of a given data point in each
#' component. \itemize{
#' \item Parameter: point - a data point.
#' }
NULL

#' @title Mixture model
#' @description Performs MCMC sampling for a mixture model.
#' @param X The data matrix to perform clustering upon (items to cluster in rows).
#' @param K The number of components to model (upper limit on the number of clusters found).
#' @param labels Vector item labels to initialise from.
#' @param dataType Int, 0: independent Gaussians, 1: Multivariate normal, or 2: Categorical distributions.
#' @param R The number of iterations to run for.
#' @param thin thinning factor for samples recorded.
#' @param concentration Vector of concentrations for mixture weights (recommended to be symmetric).
#' @return Named list of the matrix of MCMC samples generated (each row 
#' corresponds to a different sample) and BIC for each saved iteration.
sampleMixtureModel <- function(X, K, B, labels, batch_vec, proposal_window, proposal_window_for_logs, R, thin, concentration, seed) {
    .Call(`_BatchMixtureModel_sampleMixtureModel`, X, K, B, labels, batch_vec, proposal_window, proposal_window_for_logs, R, thin, concentration, seed)
}

rcpparma_hello_world <- function() {
    .Call(`_BatchMixtureModel_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BatchMixtureModel_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BatchMixtureModel_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BatchMixtureModel_rcpparma_bothproducts`, x)
}

